spring:
  application:
    name: eureka-server

server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    # Don't register itself as a client
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    hostname: localhost
  server:
    # Disable self-preservation mode in development
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    response-cache-update-interval-ms: 5000
    response-cache-auto-expiration-in-seconds: 10

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO

